
import { GoogleGenAI } from "@google/genai";

// Assume process.env.API_KEY is available
if (!process.env.API_KEY) {
  // In a real app, you'd want a more graceful way to handle this.
  // For this example, we'll throw an error to make it clear.
  // A UI prompt would be better in a production environment.
  alert("API_KEY environment variable not set. Please set it to use the application.");
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateJewelryImage(prompt: string): Promise<string> {
  const fullPrompt = `Photorealistic, intricate high-detail professional jewelry photography of: ${prompt}. The piece should be the main focus, set against a luxurious, minimalist dark background like black velvet or dark marble. Studio lighting, macro lens.`;

  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: fullPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API. The prompt might be too restrictive or the service may be unavailable.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    if (error instanceof Error && error.message.includes("API key not valid")) {
        throw new Error("The provided API Key is not valid. Please check your configuration.");
    }
    throw new Error("Failed to generate the design. Please adjust your prompt or try again later.");
  }
}
